---
title: "TPB728O Programación de aplicaciones geoespaciales en R 2021-II"
author: 
- name: Manuel Vargas
  url: https://github.com/mfvargas
  affiliation: Maestría en Sistemas de Información Geográfica y Teledetección
  affiliation_url: http://www.geo.una.ac.cr/index.php/oferta-academica/mpsigte
description: |
  Curso TPB728O Programación de aplicaciones geoespaciales en R. Maestría en Sistemas de Información Geográfica y Teledetección. Universidad de Costa Rica (UCR) y Universidad Nacional (UNA).
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

# Descripción
Este es un curso sobre desarrollo de aplicaciones geoespaciales en el lenguaje de programación [R](https://www.r-project.org/). Forma parte de la [Maestría en Sistemas de Información Geográfica y Teledetección](http://www.geo.una.ac.cr/index.php/oferta-academica/mpsigte) de la [Universidad de Costa Rica (UCR)](https://www.ucr.ac.cr/) y de la [Universidad Nacional (UNA)](https://www.una.ac.cr/).

Se estudian los fundamentos del lenguaje R, sus bibliotecas   geoespaciales   y   sus   capacidades   para   generar   gráficos estadísticos. El enfoque del curso es teórico-práctico, con lecciones teóricas combinadas con ejercicios de programación en los cuales los estudiantes aplicarán en diversos escenarios de procesamiento de datos los conocimientos adquiridos.

Este sitio web corresponde al curso impartido durante el segundo ciclo lectivo de 2021. Para ver las versiones de otros ciclos lectivos, puede visitar el [sitio web general del curso](https://tpb728O-programaciongeoespacialr.github.io/).

# Programa
[Programa del curso](https://raw.githubusercontent.com/tpb728O-programaciongeoespacialr/2021ii/main/programa/Programa%20del%20curso%20-%20TPB728O%20Programaci%C3%B3n%20de%20aplicaciones%20geoespaciales%20en%20R.pdf)

# Lecciones
[01 R - Conceptos básicos (RStudio, funciones predefinidas, tipos de datos)](leccion-01-r-conceptosbasicos.html)  
[02 R - Conceptos básicos (definición de funciones, condicionales, ciclos)](leccion-02-r-conceptosbasicos.html)  
[03 R Markdown](leccion-03-rmarkdown.html)  
[04 blogdown](leccion-04-blogdown.html)  
[05 R - Graficación](leccion-05-r-graficacion.html)  
[06 Tidyverse](leccion-06-tidyverse.html)  
[07 El ecosistema geoespacial de R](leccion-07-r-ecosistemageoespacial.html)  
[08 Operaciones de datos de atributos](leccion-08-operaciones-atributos.html)  
[09 Shiny](leccion-09-shiny.html) 

# Aplicaciones desarrolladas como ejemplo

### Distribución de la familia *Felidae* (felinos) en Costa Rica
- Documento R Markdown
    - [Código fuente](https://github.com/tpb728O-programaciongeoespacialr/2021ii-documento-felidae)
    - [Sitio web](https://tpb728o-programaciongeoespacialr.github.io/2021ii-documento-felidae/)
- Tablero de control desarrollado con flexdashboard
    - [Código fuente](https://github.com/tpb728O-programaciongeoespacialr/2021ii-flexdashboard-felidae)
    - [Sitio web](https://tpb728o-programaciongeoespacialr.github.io/2021ii-flexdashboard-felidae/)
- Tablero de control desarrollado con Shiny y shinydashboard
    - [Código fuente](https://github.com/tpb728O-programaciongeoespacialr/2021ii-shiny-shinydashboard-felidae)
    - [Sitio web](https://mfvargas.shinyapps.io/2021ii-shiny-shinydashboard-felidae/)    
- Tablero de control desarrollado con flexdashboard y Shiny
    - [Código fuente](https://github.com/tpb728O-programaciongeoespacialr/2021ii-flexdashboard-shiny-felidae)
    - [Sitio web](https://mfvargas.shinyapps.io/2021ii-flexdashboard-shiny-felidae/)        

# Tareas
[01 R Markdown](tarea-01-rmarkdown.html)  
[02 Graficación y Tidyverse](tarea-02-tidyverse.html)  

# Proyectos
[01 - Tablero de control implementado con flexdashboard](proyecto-01-flexdashboard.html)  

# Recursos
[Recursos adicionales a la bibliografía del curso](recursos.html)