---
title: "Proyecto 01 -  flexdashboard"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fecha de entrega y entregables
La fecha y hora límite para la entrega de este proyecto es el **miércoles 27 de octubre de 2021 a las 16:59**. Debe crear un sitio web, publicarlo en Netlify o en GitHub Pages, y enviarle la dirección al profesor por correo electrónico.

La tarea puede realizarse en grupos de un máximo de tres estudiantes.

## Desarrollo y calificación
El sitio web mostrará un tablero de control desarrollado con el paquete [flexdashboard](https://pkgs.rstudio.com/flexdashboard/) de R. Debe contener los siguientes componentes para un conjunto de datos que seleccionado por cada grupo (entre paréntesis, se muestra el porcentaje correspondiente de la nota final):

- (20%) Una tabla implementada con el paquete [DT](https://rstudio.github.io/DT/). La tabla debe:
    - Encabezados de columnas e interfaz general en español.
    - Funcionalidad para realizar búsquedas.

- (40%) Dos gráficos implementados con el paquete [ggplot2](https://ggplot2.tidyverse.org/) o con el paquete [plotly](https://plotly.com/r/). Puede usarse solo uno o ambos paquetes. Los gráficos deben tener:
    - Título y etiquetas en los ejes.
    - Interfaz en español.

- (40%) Un mapa implementado con el paquete [leaflet](https://rstudio.github.io/leaflet/). El mapa debe contar con:
    - Al menos dos mapas base.
    - Al menos una capa vectorial.
    - Al menos una capa raster.
    - Un control para activar y desactivar capas.
