---
title: "Recursos"
description: |
  Recursos adicionales a los mencionados en la bibliografía del curso.
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# R y RStudio
- [The R Project for Statistical Computing](https://www.r-project.org/)
- [R Language Definition](https://cran.r-project.org/doc/manuals/r-release/R-lang.html)
- [R Package Documentation](https://rdrr.io/)
- [RStudio - Open source & professional software for data science teams](https://www.rstudio.com/)
- [Hands-On Programming with R](https://rstudio-education.github.io/hopr/)
- [(Tutorial) How to Install R on Windows, Mac OS X, and Ubuntu](https://www.datacamp.com/community/tutorials/installing-R-windows-mac-ubuntu)
- [R Packages: A Beginner’s Guide](https://www.datacamp.com/community/tutorials/r-packages-guide)
- [Style guide - Advanced R](http://adv-r.had.co.nz/Style.html)
- [RStudio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/)

# Markdown y R Markdown
- [Daring Fireball: Markdown](https://daringfireball.net/projects/markdown/)
- [Markdown Guide](https://www.markdownguide.org/)
- [Markdown Cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
- [Markdown Tutorial](https://www.markdowntutorial.com/)
- [R Markdown](https://rmarkdown.rstudio.com/)
- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/)
- [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/)
- [Yihui Xie | One R Markdown Document, Fourteen Demos | RStudio (2020)](https://www.youtube.com/watch?v=qLEkUjxk7e8)

# R - Graficación
- [The R Graphics Package](http://search.r-project.org/R/library/graphics/html/graphics-package.html)  
- [Create Elegant Data Visualisations Using the Grammar of Graphics - ggplot2](https://ggplot2.tidyverse.org/)  
- [Plotly: The front end for ML and data science models](https://plotly.com/)
- [R Graphics Cookbook, 2nd edition](https://r-graphics.org/)  
- [The Grammar of Graphics](https://www.springer.com/gp/book/9780387245447)
- [A Layered Grammar of Graphics](http://vita.had.co.nz/papers/layered-grammar.pdf)
- [From data to Viz | Find the graphic you need](https://www.data-to-viz.com/)

# Tidyverse
- [Tidyverse](https://www.tidyverse.org/)
- [R for Data Science](https://r4ds.had.co.nz/)
- [R para ciencia de datos](https://es.r4ds.hadley.nz/)
- [An Antarctic Tour of the Tidyverse](https://silvia.rbind.io/talk/2020-08-31-tour-of-the-tidyverse/)
- [Data transformation with dplyr : : CHEAT SHEET](https://raw.githubusercontent.com/rstudio/cheatsheets/master/data-transformation.pdf)
- [Data visualization with ggplot2 : : CHEAT SHEET](https://raw.githubusercontent.com/rstudio/cheatsheets/master/data-visualization.pdf)

# R - Geoespacial
- [CRAN Task View: Analysis of Spatial Data](https://cran.r-project.org/web/views/Spatial.html)
- [r-spatial](http://r-spatial.org/)
- [Spatial Data Science with R - R Spatial](https://rspatial.org/)
- [Simple Features for R - sf](https://r-spatial.github.io/sf/)
- [The raster package - R Spatial](https://rspatial.org/raster/pkg/)
- [The terra package - R Spatial](https://rspatial.org/terra/pkg/)
- [Leaflet for R](https://rstudio.github.io/leaflet/)
- [tmap - R package for thematic maps](https://github.com/mtennekes/tmap)
- [Interactive viewing of spatial data in R - mapview](https://r-spatial.github.io/mapview/)
- [Spatiotemporal Arrays: Raster and Vector Datacubes - stars](https://r-spatial.github.io/stars/)
- [Geocomputation with R](https://geocompr.robinlovelace.net/)
- [R for Geographic Data Science](https://sdesabbata.github.io/r-for-geographic-data-science/)
- [Spatial Data Science with applications in R](https://keen-swartz-3146c4.netlify.app/)
- [Drawing beautiful maps programmatically with R, sf and ggplot2](http://r-spatial.org/r/2018/10/25/ggplot2-sf.html)
- [R-Ladies Madrid (español) - Analiza datos espaciales](https://www.youtube.com/watch?v=59tO2ARvVVU&t=5680s)
- [Materiales del taller "R-Ladies Madrid (español) - Analiza datos espaciales"](https://github.com/sporella/datos_espaciales_madrid)

# flexdashboard
- [R Markdown Format for Flexible Dashboards - flexdashboard](https://pkgs.rstudio.com/flexdashboard/)

# Shiny
- [Shiny](https://shiny.rstudio.com/)
- [Shiny - tutorial](https://shiny.rstudio.com/tutorial/)
- [Mastering Shiny](https://mastering-shiny.org/)
- [Shiny Dashboard](https://rstudio.github.io/shinydashboard/)
- [Using shiny with flexdashboard](https://rstudio.github.io/flexdashboard/articles/shiny.html)
- [Building an interactive dashboard to visualize spatial data](https://www.paulamoraga.com/tutorial-flexdashboard/)
- [Geospatial Health Data: Modeling and Visualization with R-INLA and Shiny - Building a dashboard to visualize spatial data with flexdashboard](https://www.paulamoraga.com/book-geospatial/sec-flexdashboard.html)
- [Create an Interactive Dashboard with Shiny, Flexdashboard, and Plotly](https://towardsdatascience.com/create-an-interactive-dashboard-with-shiny-flexdashboard-and-plotly-b1f025aebc9c)
- [Shiny Dashboards with Flexdashboard](https://medium.com/analytics-vidhya/shiny-dashboards-with-flexdashboard-e66aaafac1f2)
- [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org/)
- [TidyTuesday: Flexdashboard vs Shinydashboard](https://www.youtube.com/watch?v=AVmfWL43B70)